# Generated by Django 5.0.2 on 2024-01-05 18:57

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=21, verbose_name=builtins.id),
            preserve_default=False,
        ),
    ]
