# Generated by Django 5.0.2 on 2024-04-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
