# Generated by Django 5.0.2 on 2024-05-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_remove_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_title',
            field=models.CharField(default=132, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='descriptive_text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
