# Generated by Django 5.0.2 on 2024-05-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0004_order_order_title_alter_order_descriptive_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='descriptive_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
