# Generated by Django 5.0.2 on 2024-07-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0005_alter_order_descriptive_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending approval', 'pending approval'), ('completed', 'completed'), ('in-transit', 'in-transit')], default='pending approval', max_length=50),
        ),
    ]
